version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.4
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${RAILWAY_STATIC_URL:-kafka}:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    volumes:
      - kafka_data:/bitnami
    ports:
      - "9092:9092"
    restart: unless-stopped

  kafka-setup:
    image: bitnami/kafka:3.4
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./kafka-setup.sh:/scripts/setup.sh
    command: ["bash", "/scripts/setup.sh"]
    restart: on-failure

volumes:
  zookeeper_data:
  kafka_data:
